apiVersion: v1
kind: ConfigMap
metadata:
  name: organization
  labels:
    app: organization
data:
  application.yaml: |-
    mongodb:
      collection: organization
      database: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: organization
  labels:
    app: organization
type: Opaque
data:
  mongodb.uri: bW9uZ29kYjovL21pY3JvbmF1dDptaWNyb25hdXRfMTIzQG1vbmdvZGI6MjcwMTcvYWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization
  labels:
    app: organization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      containers:
        - name: organization
          image: piomin/organization
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: organization
  labels:
    app: organization
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: organization
  type: NodePort